// Generated by https://quicktype.io

export interface Employee {
  id:          number;
  created_at:  string;
  nombre:      string;
  apellidos:   string;
  descripcion: string;
  ci:          number;
  password:    string;
  rol:         number;
}
